---
- name: Play 1
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create /tmp/testfile.txt
      file:
        path: /tmp/testfile.txt
        state: touch
        
- name: Play 2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create /tmp/testfile.txt
      file:
        path: /tmp/testfile.txt
        state: touch
